#print("Hello World!")
# print("What is your name")
# name = input()
# print("Hello, " + name)
print("Enter first number")
first = int(input())
print("Enter second number")
second = int(input())
sum = first + second
print("sum:",sum)